In [1]:
import numpy as np

In [3]:
a = np.arrange(6)

AttributeError: module 'numpy' has no attribute 'arrange'

In [5]:
a = np.arange(6)

In [7]:
type(a)

numpy.ndarray

In [9]:
a

array([0, 1, 2, 3, 4, 5])

In [11]:
a[0]

0

In [13]:
a[1]

1

In [15]:
a[:]

array([0, 1, 2, 3, 4, 5])

In [17]:
a[np.nawaxis, :]

AttributeError: module 'numpy' has no attribute 'nawaxis'

In [23]:
a2 = a[np.newaxis, :] #성영 2차원으로 2개의 배열생성 [[]] 대괄호 2개포 표시됨

In [25]:
a2.shape

(1, 6)

In [27]:
a.shape

(6,)

In [29]:
a[3]

3

In [35]:
a = np.array([[1,2,3,4],[5,6,7,8]. [9,10,11,12]])

SyntaxError: invalid syntax (2925620721.py, line 1)

In [37]:
a = np.array([1,2,3,4])

In [39]:
print(a[])

SyntaxError: invalid syntax. Perhaps you forgot a comma? (2129586007.py, line 1)

In [41]:
a

array([1, 2, 3, 4])

In [43]:
a = np.array([[1,2,3,4,], [5,6,7,8], [9,10,11,12]])

In [45]:
p

NameError: name 'p' is not defined

In [47]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [49]:
a[0]

array([1, 2, 3, 4])

In [51]:
a[1]

array([5, 6, 7, 8])

In [53]:
a[0,1]

2

In [55]:
a[2]

array([ 9, 10, 11, 12])

In [57]:
a = np.array([1, 2, 3])

In [59]:
na.zeros(2)

NameError: name 'na' is not defined

In [61]:
np.zeros(2)

array([0., 0.])

In [63]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [65]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [69]:
np.empty(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [71]:
np.arange(2, 8, 2)

array([2, 4, 6])

In [73]:
np.arange(2, 9, 3)

array([2, 5, 8])

In [87]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [89]:
a = 1.

In [91]:
type(a)

float

In [97]:
b = np.ones(2, dtype = np.float64)

In [99]:
b

array([1., 1.])

In [101]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [103]:
arr

array([2, 1, 5, 3, 7, 4, 6, 8])

In [107]:
c = np.sort(arr)

In [109]:
c

array([1, 2, 3, 4, 5, 6, 7, 8])

In [111]:
arr

array([2, 1, 5, 3, 7, 4, 6, 8])

In [113]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [117]:
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [129]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

In [131]:
x

array([[1, 2],
       [3, 4]])

In [133]:
y

array([[5, 6],
       [7, 8]])

In [139]:
np.concatenate((x, y), axis = 0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [143]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                           [[0, 1, 2, 3],
                            [4, 5, 6, 7]],

                           [[0, 1, 2, 3],
                            [4, 5, 6, 7]]])

In [145]:
array_example.ndim

3

In [147]:
array_example.size

24

In [149]:
array_example.shape #성영 ; 3 x 2 x 4 요소개수. 가장 바깥 3차원, 차원에 2개씩, 4개 요소로 구성

(3, 2, 4)

In [151]:
a = np.array(6)

In [153]:
a

array(6)

In [155]:
a = np.arange(6)

In [157]:
a

array([0, 1, 2, 3, 4, 5])

In [161]:
a.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [163]:
a.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [165]:
np.reshape(a, newshape=(1, 6), order='C')

array([[0, 1, 2, 3, 4, 5]])

In [167]:
a = np.array([1, 2, 3, 4, 5, 6])

In [169]:
a.shape

(6,)

In [171]:
a2 = a[np.newaxis, :] #성영 - 2차원 array로 변경

In [173]:
a2

array([[1, 2, 3, 4, 5, 6]])

In [175]:
a2.shape

(1, 6)

In [177]:
data = np.array([1, 2, 3])

In [179]:
data[1]

2

In [181]:
data[0:2]

array([1, 2])

In [183]:
data[0:3]

array([1, 2, 3])

In [185]:
data[-2:] # 성영 리스트와 동일 -2는 끝에서 2번째

array([2, 3])

In [187]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [189]:
print(a[a < 5])

[1 2 3 4]


In [191]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [193]:
a > 5

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [195]:
five_up = (a >= 5)

In [197]:
five_up

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [199]:
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [201]:
a[a >= 5]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [203]:
a%2 == 0

array([[False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True]])

In [205]:
a[a%2 == 0]

array([ 2,  4,  6,  8, 10, 12])

In [209]:
a[(a > 2) & (a < 11)]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [211]:
a[(a > 5) | (a ==5)]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [213]:
np.nonzero(a < 5)

(array([0, 0, 0, 0], dtype=int64), array([0, 1, 2, 3], dtype=int64))

In [227]:
b = np.nonzero(a < 5)

In [231]:
print(b)

(array([0, 0, 0, 0], dtype=int64), array([0, 1, 2, 3], dtype=int64))


In [233]:
list_of_coordinates = list(zip(b[0], b[1]))

In [235]:
list_of_coordinates

[(0, 0), (0, 1), (0, 2), (0, 3)]

In [225]:
print(b)

(array([0, 0, 0, 0], dtype=int64), array([0, 1, 2, 3], dtype=int64))


In [237]:
for coord in list_of_coordinates:
    print(coord)

(0, 0)
(0, 1)
(0, 2)
(0, 3)


In [239]:
a1 = np.array([[1, 1],
               [2, 2]])
a2 = np.array([[3, 3],
               [4, 4]])

In [241]:
np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [243]:
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [245]:
np.arange(1, 15).reshape(2, 7)

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [247]:
x = np.arange(1, 25).reshape(2, 12)

In [249]:
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [251]:
np.hsplit(x, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [255]:
np.hsplit(x, (3, 6, 8))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4,  5,  6],
        [16, 17, 18]]),
 array([[ 7,  8],
        [19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [1]:
import numpy as np

In [3]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [5]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [7]:
b1 = a[0, :]

In [9]:
b1

array([1, 2, 3, 4])

In [11]:
b1[0] = 99

In [13]:
b1

array([99,  2,  3,  4])

In [15]:
a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [17]:
a = np.array([1, 2, 3, 4])

In [19]:
a

array([1, 2, 3, 4])

In [21]:
a.sum()

10

In [25]:
b = np.array([[1, 2], [3, 4]])

In [27]:
b.sum(axis = 0)

array([4, 6])

In [29]:
b.sum(axis=1)

array([3, 7])

In [31]:
b

array([[1, 2],
       [3, 4]])

In [33]:
a.max()

4

In [35]:
a.min()

1

In [37]:
c = a * 2

In [39]:
c

array([2, 4, 6, 8])

In [43]:
b = np.array([[1, 4], [2, 7]])

In [45]:
b.min(axis=0)

array([1, 4])

In [47]:
b

array([[1, 4],
       [2, 7]])

In [49]:
b.min(axis=1)

array([1, 2])

In [51]:
data = np.array([[1, 2], [3, 4], [5, 6]])

In [53]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [55]:
data[0, 1]

2

In [57]:
data[1:3]

array([[3, 4],
       [5, 6]])

In [61]:
data[0:2]

array([[1, 2],
       [3, 4]])

In [63]:
data[0:2, 0] #성영 [행, 열] 이므로, 행의 첫째(0)에서 둘째전까지(1) data를 가져온 후, 그 중에서 첫째 열(0) data 만 추출

array([1, 3])

In [13]:
np.ones(3)

array([1., 1., 1.])

In [15]:
np.zeros(3)

array([0., 0., 0.])

In [17]:
rng = np.random.default_rng()  # the simplest way to generate random numbers
rng.random(3)

array([0.56505983, 0.34423347, 0.20534894])

In [11]:
rng.integers(5, size=(2, 4))

array([[3, 2, 3, 4],
       [0, 0, 3, 2]], dtype=int64)

In [65]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [67]:
np.unique(a)

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [71]:
np.unique(a, return_index=True)

(array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20]),
 array([ 0,  2,  3,  4,  5,  6,  7, 12, 13, 14], dtype=int64))

In [19]:
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])

In [25]:
uniq_value = np.unique(a_2d)

In [27]:
print(uniq_value)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [29]:
np.unique(a_2d, axis = 0) # 성영 : row(axis=0) 기준으로 고유값

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [37]:
arr = np.arange(6).reshape((2, 3))

In [39]:
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [41]:
arr.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [45]:
arr.T #성영 : 대문자 T 만으로도 transpose 가

array([[0, 3],
       [1, 4],
       [2, 5]])

In [47]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [49]:
reversed_arr = np.flip(arr) #성영 : 순서를 바꾼다. flipped

In [51]:
print('Reversed Array: ', reversed_arr)

Reversed Array:  [8 7 6 5 4 3 2 1]


In [53]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [55]:
reversed_arr = np.flip(arr_2d) #성영 : 2차원 배열을 뒤집다. 
print(reversed_arr)

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [57]:
reversed_arr_rows = np.flip(arr_2d, axis=0) #성영 : Row의 순서만 바뀌고, Row내에서 순서는 유지
print(reversed_arr_rows)

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [59]:
reversed_arr_columns = np.flip(arr_2d, axis=1) #성영 : column 순서만 바뀌고, row 순서는 유지
print(reversed_arr_columns)

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


In [61]:
arr_2d[1] = np.flip(arr_2d[1]) #성영 : 1번째 row내의 순서만 바꿈
print(arr_2d)

[[ 1  2  3  4]
 [ 8  7  6  5]
 [ 9 10 11 12]]


In [63]:
arr_2d[:,1] = np.flip(arr_2d[:,1]) #성영 : 1번째 column 내의 순서만 바꿈
print(arr_2d)

[[ 1 10  3  4]
 [ 8  7  6  5]
 [ 9  2 11 12]]


In [71]:
x = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [73]:
x.flatten() #성영 : 1차원 배열로 묶어서 변환

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [75]:
a1 = x.flatten()
a1[0] = 99 #성영 : a1 배열의 1번째 요소에 99을 입력
print(x)  # Original array
print(a1)  # New array

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[99  2  3  4  5  6  7  8  9 10 11 12]


In [77]:
a2 = x.ravel()
a2[0] = 98 # 성영 : 첫째 요소에 98 입력하면, 그 이전 상위 배열(x)까지 변경됨
print(x)  # Original array
print(a2)  # New array

[[98  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[98  2  3  4  5  6  7  8  9 10 11 12]
